# Generated by Django 6.1.1 on 2026-10-04 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_google_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='file_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lang1', models.CharField(default='fr', max_length=16)),
                ('lang2', models.CharField(default='ar', max_length=16)),
                ('files', models.JSONField(blank=True, default=list)),
                ('client_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('user', 'client_id'), name='unique_user_folder_client_id')],
            },
        ),
    ]
